#import "../../src/lib.typ": *

#heading(
  level: 1, 
  [Guía del Lector],
  outlined: true,
  bookmarked: true,
  numbering: none
)

El presente documento de investigación ha sido organizado por secciones para facilitar su comprensión, servir de hoja de ruta al lector y optimizar la navegación entre los distintos capítulos. A continuación, se describe de manera concisa el contenido y la estructura de cada apartado, resaltando sus objetivos principales y la lógica de su secuencia.

#init-acronyms((
  "LMS": ("Learning Management System", "Sistema de Gestión del Aprendizaje"),
  "TI": ("Tecnologías de la Información"),
  "TIC": ("Tecnologías de la Información y Comunicación"),
  "UCD": ("User-Centered Design", "Diseño Centrado en el Usuario"),
  "RNF": ("Requisitos No Funcionales"),
  "API Gateway": ("Application Programming Interface Gateway", "Puerta de Enlace de Interfaz de Programación de Aplicaciones"),
  "CI/CD": ("Continuous Integration/Continuous Delivery", "Integración Continua/Entrega Continua"),
  "IaC": ("Infrastructure as Code", "Infraestructura como Código"),
  "Frontend": ("Capa de Presentación", "Parte del sistema con la que el usuario interactúa directamente"),
  "Backend": ("Capa de Lógica de Negocio y Datos", "Parte del sistema que gestiona la lógica y los datos detrás de la interfaz de usuario"),
  "Microservicios": ("Arquitectura de Software Distribuido", "Estilo arquitectónico que estructura una aplicación como una colección de servicios pequeños e independientes"),
  "Docker": ("Plataforma de Contenerización", "Herramienta para empaquetar, distribuir y ejecutar aplicaciones en contenedores"),
  "Kubernetes": ("Sistema de Orquestación de Contenedores", "Plataforma de código abierto para automatizar el despliegue, escalado y gestión de aplicaciones en contenedores"),
  "PostgreSQL": ("Sistema de Gestión de Bases de Datos Relacionales", "Base de datos de código abierto, potente y robusta"),
  "MongoDB": ("Base de Datos NoSQL Orientada a Documentos", "Base de datos NoSQL flexible para datos semi-estructurados"),
  "InfluxDB": ("Base de Datos de Series de Tiempo", "Base de datos optimizada para el almacenamiento y análisis de datos temporales"),
  "Redis": ("Almacén de Datos en Memoria", "Base de datos en memoria, utilizada para caching y mensajería"),
  "NoSQL": ("Not Only SQL", "No Solo SQL"),
  "ORM": ("Object-Relational Mapping", "Mapeo Objeto-Relacional"),
  "DAL": ("Data Access Layer", "Capa de Acceso a Datos"),
  "ACID": ("Atomicity, Consistency, Isolation, Durability", "Atomicidad, Consistencia, Aislamiento, Durabilidad"),
  "JWT": ("JSON Web Token", "Token Web JSON"),
  "POJO": ("Plain Old Java Object", "Objeto Java Simple"),
  "DTO": ("Data Transfer Object", "Objeto de Transferencia de Datos"),
  "Pub/Sub": ("Publish/Subscribe", "Publicación/Suscripción"),
  "Eureka Server": ("Servidor Eureka", "Servidor de Descubrimiento de Servicios"),
  "Config Server": ("Servidor de Configuración", "Servidor de Gestión Centralizada de Configuraciones"),
  "ELK Stack": ("Elasticsearch, Logstash, Kibana", "Conjunto de herramientas para agregación y análisis de logs"),
  "Angular": ("Framework de Desarrollo Frontend", "Plataforma de código abierto para construir interfaces de usuario en el lado del cliente"),
  "Spring Boot": ("Framework de Desarrollo Backend", "Marco de trabajo de código abierto para construir aplicaciones Java rápidamente"),
  "RabbitMQ": ("Broker de Mensajes", "Software de mensajería de código abierto que implementa el estándar AMQP"),
  "Kafka": ("Plataforma de Streaming Distribuido", "Sistema de cola de mensajes distribuido, diseñado para procesar flujos de datos en tiempo real"),
  "Supabase": ("Backend as a Service", "Plataforma de código abierto que ofrece funcionalidades de backend, incluyendo base de datos PostgreSQL, autenticación, almacenamiento y funciones de borde"),
  "Vercel": ("Plataforma de Desarrollo y Despliegue Frontend", "Plataforma para el despliegue rápido y escalable de aplicaciones web frontend"),
  "Render": ("Plataforma Cloud Unificada", "Plataforma para alojar servicios web, APIs y bases de datos con escalado automático"),
  "GitHub Actions": ("Plataforma de CI/CD", "Herramienta de automatización para flujos de trabajo de desarrollo de software en GitHub"),
  "Terraform": ("Herramienta de Infraestructura como Código", "Herramienta para construir, cambiar y versionar la infraestructura de forma segura y eficiente"),
  "SQL": ("Structured Query Language", "Lenguaje de Consulta Estructurado"),
  "Migrations": ("Migraciones de Base de Datos", "Cambios estructurados y versionados aplicados al esquema de una base de datos"),
  "Frontend Hosting": ("Alojamiento Frontend", "Servicio para almacenar y servir los archivos estáticos de una aplicación web de cara al usuario"),
  "Backend Hosting": ("Alojamiento Backend", "Servicio para desplegar y ejecutar la lógica de servidor de una aplicación"),
  "Autenticación (Auth)": ("Gestión de Acceso", "Proceso de verificar la identidad de un usuario, sistema o proceso"),
  "Monitoreo": ("Supervisión del Sistema", "Proceso de observar y recolectar datos sobre el rendimiento y el comportamiento de un sistema"),
  "Logging": ("Registro de Eventos", "Proceso de registrar eventos o mensajes generados por un sistema o aplicación"),
  "DevOps": ("Desarrollo y Operaciones", "Conjunto de prácticas que combinan el desarrollo de software (Dev) y las operaciones de TI (Ops) para acortar el ciclo de vida de desarrollo de sistemas"),
  "Git": ("Sistema de Control de Versiones Distribuido", "Herramienta para el seguimiento de cambios en el código fuente durante el desarrollo de software"),
  "YAML": ("YAML Ain't Markup Language", "Lenguaje de serialización de datos legible por humanos"),
  "TypeScript": ("Superset de JavaScript", "Lenguaje de programación de código abierto que añade tipado estático a JavaScript"),
  "JDBC": ("Java Database Connectivity", "API de Java para conectar con bases de datos relacionales"),
  "REST API": ("Representational State Transfer Application Programming Interface", "Estilo de arquitectura de software para construir APIs web que utilizan solicitudes HTTP"),
  "JSON": ("JavaScript Object Notation", "Formato ligero de intercambio de datos"),
  "API RESTful": ("Interfaz de Programación de Aplicaciones RESTful", "API que adhiere a los principios del estilo arquitectónico REST"),
  "OAuth 2.0": ("Open Authorization 2.0", "Marco de autorización que permite a las aplicaciones obtener acceso limitado a cuentas de usuario en un servicio HTTP"),
  "Scalability": ("Escalabilidad", "Capacidad de un sistema de manejar una cantidad creciente de trabajo o su potencial para ser ampliado"),
  "Resilience": ("Resiliencia", "Capacidad de un sistema para recuperarse de fallos y seguir funcionando"),
))

#pagebreak()