server:
  port: 8083

spring:
  application:
    name: resource-planning-service
  r2dbc:
    url: r2dbc:postgresql://<project-ref>.supabase.co:5432/<db-name>
    username: postgres
    password: <YOUR_SUPABASE_DB_PASSWORD>
  
# Configuración de Eureka Client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      #TODO: Cambiar dado que se abrirá un contenedor docker
      hostname: localhost 
      # instance-id: ${spring.application.name}:${instanceId:${random.value}} # Opcional: ID única para cada instancia
  