spring:
  application:
    name: resource-planning-service
  config:
    import: "configserver:http://localhost:8888"

SUPABASE_PROJECT_REF_IMPORTED: ${SUPABASE_PROJECT_REF_IMPORTED}
SUPABASE_DB_PASSWORD: ${SUPABASE_DB_PASSWORD}
