= Conclusiones

En esta sección final, se presenta una síntesis de los avances logrados en el desarrollo del Sistema de Gestión del Aprendizaje (LMS). Se ha establecido la estructura fundamental del sistema, desde la definición de sus identidades y relaciones hasta la creación de una arquitectura robusta y la implementación de *endpoints* y una API que dotan de funcionalidad a la parte *backend*. Este análisis conclusivo evaluará el progreso en la consecución de los objetivos planteados y la infraestructura actual, desarrollando los hitos logrados y faltantes para el cumplimiento de la propuesta presentada.

*PRIMERO*: El proceso de diagnóstico inicial, diseñado para comprender a fondo la infraestructura, los sistemas existentes y las competencias digitales, ha culminado en la definición exhaustiva de identidades únicas y sus relaciones. Esto ha permitido establecer la estructura principal de cómo se estructurará la información dentro del LMS, basándose en los procesos estandarizados del AEP y la estructuración de análisis número-estadísticos. De esta manera, en esta fase se logró completar el periodo estimado y, a su vez, ha proporcionado una comprensión detallada de las condiciones de partida del proyecto, sentando así una base sólida y bien organizada que guiará el desarrollo posterior del sistema y, de forma adyacente, la definición de hitos y logros que deberá abarcar un sistema LMS.

*SEGUNDO*: La identificación y documentación detallada de los procesos conllevó al desarrollo y definición de los factores funcionales y no funcionales del LMS, un paso que dio forma al diseño del sistema y ha encontrado su concreción en la creación y definición de una arquitectura robusta relacionada con la escalabilidad y resiliencia de servicios procedimentales identificados, siendo que estas necesidades y deseos se han transformado en un mapa técnico tangible que va más allá de una simple maquetación. De esta forma, la implicación directa del presente diseño es la creación de wireframes y mockups, el cual permite que el sistema ya no sea solo una idea en papel, sino que posee una estructura definida y validada; de esta manera se ha superado la fase conceptual y logrado la concreción del diseño técnico que se convierte en la forma ideal definida.

*TERCERO*: Durante la fase de diseño de la arquitectura modular y los componentes clave del prototipo funcional, se ha alcanzado un hito significativo con la creación de los *endpoints*. La existencia de estos *endpoints* implica que los elementos fundamentales de la arquitectura han dejado de ser abstractos para convertirse en puntos de acceso funcionales que permiten la interacción y el flujo de datos. Si bien esta relevancia en el momento actual radica en que estos *endpoints*, al ser el puente para la captura de información, validan la efectividad del diseño y permiten que el prototipo comience a tomar forma, ayudará a posibilitar la comunicación entre las distintas partes del sistema de forma estructurada y brindando la base para una escalabilidad futura.

*CUARTO*: La implementación de un prototipo funcional ha avanzado considerablemente con la puesta en marcha de una API relacionada para la captura de información, brindando la funcionalidad activa y básica para la identificación de problemas y testeos de compatibilidad con requisitos funcionales. Por lo que, en definición de las fechas planteadas y hitos definidos, tiene una gran relación con la continuidad y cumplimiento de la programación lógica del cronograma, siendo que la fase de desarrollo más técnica, la del *backend*, ha conseguido que los componentes principales se comuniquen y procesen datos, brindando así la operatividad inicial y sienta un precedente favorable para la compatibilidad futura con dispositivos de bajo costo y la creación de la propuesta.

*QUINTO*: Respecto a la evaluación del desempeño, la usabilidad y la percepción de valor del prototipo, aunque la capa de *frontend* aún no se ha desarrollado, la funcionalidad operativa de los *endpoints* y la API ya permite inferir la viabilidad técnica subyacente del sistema. Esta inferencia significa que, a pesar de la imposibilidad de realizar pruebas de usabilidad completas sin la interfaz de usuario, ya se puede confirmar la capacidad del *backend* para procesar las interacciones y manejar los datos, lo que representa un indicador clave de que el prototipo está preparado para una evaluación exhaustiva una vez que se complete la capa visible para el usuario final, lo que permitirá finalmente cuantificar su impacto y las áreas de mejora.

#pagebreak()