#import "../../src/lib.typ"

= Introducción

A partir de la investigación de este proyecto, se propone el desarrollo de una plataforma digital que facilite la enseñanza y el aprendizaje adaptativo en instituciones especializadas. A diferencia de otros sistemas de aprendizaje, este sistema e-learning (LMS) se caracterizará por ser interactivo, descentralizado, con un enfoque en la gestión inteligente de contenidos formativos y el seguimiento de estudiantes a través de la definición de métricas, promoviendo la colaboración docente-alumno de forma síncrona y asíncrona (Betancourt, L. A. et al., 2020)#footnote[Betancourt, L. A., Moya Joniaux, C. A., Vera Crespo, M. D., Corral Joniaux, J. A., & Olaya Reyes, J. J. (2020). Vínculo universidad–empresa: vía para la formación profesional del estudiante. Revista Espacios, 41(13), 14-22.]. De este modo, se busca no solo trasladar la enseñanza a entornos virtuales, sino aprovechar la tecnología para personalizar el aprendizaje y mejorar los resultados educativos, tal como señalan diversas investigaciones.

En este contexto, un Sistema de Gestión del Aprendizaje (LMS) se muestra como una herramienta de software cuyo propósito fundamental es la entrega, gestión y seguimiento de contenido educativo y recursos a los usuarios finales. Su función principal radica en centralizar y optimizar el proceso de enseñanza y aprendizaje, promoviendo la eficiencia, accesibilidad y capacidad de medición de los resultados. Estas plataformas permiten a los educadores y administradores una gestión exhaustiva de los cursos, incluyendo la inscripción de alumnos, la asignación de tutores, la creación de evaluaciones en línea y el seguimiento detallado del progreso individual.

Sin embargo, históricamente, los LMS se diseñaron principalmente para la distribución de contenido, la gestión de funciones administrativas y la provisión de herramientas básicas de comunicación. Su enfoque inicial estaba en la organización de materiales y la automatización de tareas, lo que representaba un avance significativo respecto a los métodos tradicionales. No obstante, estas plataformas tradicionales fueron objeto de críticas debido a su inherente rigidez, su incapacidad para adaptarse a las diversas necesidades de los estudiantes individuales y la limitada interacción que ofrecían. El modelo "talla única" predominante no lograba satisfacer la heterogeneidad de estilos y ritmos de aprendizaje, lo que a menudo resultaba en experiencias educativas pasivas y poco motivadoras.

Frente a estas limitaciones, la evolución contemporánea con la nueva era de la Web 4, los LMS marcan una transición fundamental hacia entornos de aprendizaje considerablemente más dinámicos y personalizados. Esta transformación está intrínsecamente impulsada por la integración de tecnologías avanzadas, destacando la Inteligencia Artificial (IA) y el aprendizaje adaptativo. El propósito de esta evolución es trascender la mera entrega de contenido, buscando en cambio ofrecer experiencias de aprendizaje enriquecedoras, inmersivas y profundamente interactivas. Este cambio de paradigma implica que el LMS ha dejado de ser una herramienta puramente administrativa para la gestión de cursos, para convertirse en un componente pedagógico central. Su diseño actual se enfoca en la optimización del proceso de aprendizaje en sí mismo, adaptándose de manera proactiva a las necesidades individuales de cada alumno. Esta redefinición de su propósito y diseño, conlleva en una mejora considerable en la comprensión del potencial transformador de los LMS en la educación moderna.

De esta manera, en compración con esta tendencia global, en el Perú, la adopción de plataformas educativas ha crecido notablemente tras la pandemia de COVID-19. Iniciativas como “Aprendo en Casa” y planes nacionales de conectividad han impulsado el uso de herramientas digitales en colegios y universidades, aunque persisten brechas de acceso y habilidades tecnológicas. Del mismo modo, estudios internacionales muestran que el interés por los LMS en la educación superior es mundial, aunque la mayoría de investigaciones provienen de Estados Unidos y reportan un uso aún básico de estas plataformas (p.ej., envío de correos o compartición de archivos). No obstante, se reconoce globalmente que las plataformas LMS (como Moodle, Canvas o Blackboard) brindan mayor acceso, flexibilidad y continuidad al proceso educativo. En este sentido, la UNESCO (2023)#footnote[UNESCO. (2023). Informe de seguimiento de la educación en el mundo 2023: Tecnología en la educación. UNESCO.] destaca que las tecnologías digitales deben emplearse para apoyar una educación centrada en la interacción humana, ampliando el alcance pedagógico en formatos atractivos y equitativos. Comparativamente, las universidades peruanas han comenzado proyectos de transformación digital integrales, creando unidades de gestión tecnológica y fomentando competencias digitales en docentes y alumnos. Sin embargo, el reto persiste en adaptar el currículo y las metodologías de enseñanza a estas nuevas modalidades.

== Educación Académica Productiva
Uno de los objetivos clave de este LMS interactivo es superar la desconexión entre la educación especializada y el mundo laboral. Diversos estudios, sobre todo en Latinoamérica, señalan una brecha importante entre la oferta educativa y las necesidades del mercado, lo que dificulta el desarrollo económico y la empleabilidad. La Corporación Andina de Fomento (CAF, 2015)#footnote[Corporación Andina de Fomento. (2015). Educación técnica y formación profesional en Perú. CAF.] indica que el 35% de las empresas a nivel mundial y un 39% en Latinoamérica tienen problemas para cubrir puestos por falta de personal cualificado. Esto subraya la necesidad de formar "capital humano con las competencias necesarias" para adaptarse a la innovación tecnológica y a las demandas del mercado global.

En este contexto, la colaboración entre universidades y empresas es crucial. Betancourt et al. (2020)#footnote[Betancourt, L. A., Moya Joniaux, C. A., Vera Crespo, M. D., Corral Joniaux, J. A., & Olaya Reyes, J. J. (2020). Vínculo universidad–empresa: vía para la formación profesional del estudiante. Revista Espacios, 41(13), 14-22.] afirman que esta conexión es fundamental para que los estudiantes integren la teoría con la práctica profesional real. Esta colaboración expone a los estudiantes a situaciones reales y permite a las instituciones educativas actualizar sus programas para alinearlos con las tendencias de la industria. Al promover esta relación, se asegura que los egresados tengan las habilidades técnicas y sociales (como pensamiento crítico y adaptabilidad) que valoran los empleadores. La participación en proyectos, las prácticas preprofesionales y la mentoría son mecanismos clave para fortalecer este vínculo.

Por lo tanto, el LMS propuesto facilita la articulación de contenidos y ejercicios directamente relacionados con perfiles profesionales específicos. Más que un repositorio de información, esta plataforma promueve activamente acuerdos y proyectos colaborativos entre instituciones educativas y empresas. La capacidad que se espera que tengal el LMS para integrar datos sobre el rendimiento estudiantil con las demandas del mercado laboral permitirá identificar las competencias más valoradas y adaptar los itinerarios de aprendizaje. Mediante módulos interactivos que simulan entornos laborales reales, ejercicios prácticos y oportunidades de mentoría virtual, el LMS actúa como un puente entre la educación y el mundo laboral. Esto prepara a los estudiantes con las habilidades necesarias y fomenta una mentalidad proactiva y adaptable, esencial para su éxito profesional. En definitiva, un LMS con estas características contribuye a formar profesionales más competentes, mejorando su empleabilidad y el desarrollo socioeconómico.

== Educación Superior Especializada e Instructiva
Dado lo anterior, este proyecto se enfoca en el desarrollo de una plataforma e-learning orientada a instituciones de educación superior de carácter técnico-profesional y universidades especializadas, así como a empresas interesadas en la formación continua de su personal. Aunque un sistema educativo robusto podría beneficiar a niveles pedagógicos más básicos como colegios y escuelas, la urgencia de las organizaciones por invertir en la cualificación de sus trabajadores y obtener un retorno de inversión en sus programas de capacitación dirige la atención hacia soluciones flexibles.  

Para estas entidades, el LMS debe incluir no solo módulos prácticos y evaluaciones simuladas, sino también la capacidad de ofrecer rutas de aprendizaje personalizadas y accesibilidad multidispositivo, lo que permite a las empresas capacitar a sus empleados de forma eficiente y según estándares académicos actualizados (SAP, s.f.; Cursalab, 2022)#footnote[¿Qué es un LMS? | SAP SuccessFactors. (s. f.). SAP. https://www.sap.com/spain/products/hcm/corporate-lms/what-is-lms.html]. Un LMS corporativo, por ejemplo, centraliza y simplifica la gestión de la formación, reduce costos asociados a la capacitación tradicional (como viajes y materiales impresos), y ofrece flexibilidad horaria y geográfica, aspectos cruciales para equipos distribuidos o con horarios complejos. Además, herramientas de análisis y seguimiento de progreso permiten a las organizaciones evaluar el impacto de la formación y asegurar el cumplimiento normativo, optimizando así la inversión en desarrollo de talento.

De esta manera, el LMS servirá como un puente entre la academia y el sector productivo, alineando los planes de estudio con las necesidades laborales específicas, tal como recomiendan estudios (Romero Carbonell et al., 2023)#footnote[Romero Carbonell, M., Romeu Fontanillas, T., Guitert Catasús, M., & Baztán Pujadas, P. (2023). La transformación digital en la educación superior: el caso de la UOC. RIED: Revista Iberoamericana de Educación a Distancia, 26(1), 163-179.]. Así, esta plataforma contribuirá significativamente a la innovación tecnológica mediante una formación profesional más pertinente y adaptable, lo que a su vez mejorará la competitividad de los graduados y reducirá la persistente brecha "académica-productiva" en el Perú.

== Consideraciones Tecnológicas, Pedagógicas e Institucionales
El diseño e implementación de un LMS efectivo trasciende la mera instalación de software, requiriendo un enfoque integral que aborde factores contextuales clave: tecnológicos, pedagógicos e institucionales.

Desde el punto de vista tecnológico, es fundamental garantizar una infraestructura informática adecuada. Esto incluye no solo servidores robustos y conectividad a internet fiable, sino también la compatibilidad con diversos dispositivos para asegurar la accesibilidad. Por lo que, seleccionar un software que sea escalable, preferiblemente de código abierto para permitir una mayor personalización y adaptabilidad, y que soporte la interacción multimedia para enriquecer la experiencia de aprendizaje. La elección de tecnologías debe prever el crecimiento de usuarios y el volumen de contenido, asegurando un rendimiento óptimo y una experiencia fluida.

Desde la perspectiva pedagógica, el sistema debe ir más allá de la simple distribución de contenido. Necesita incorporar enfoques modernos que promuevan un aprendizaje activo y significativo. Esto implica integrar herramientas para el aprendizaje colaborativo, facilitando la interacción entre estudiantes y docentes; ofrecer mecanismos de retroalimentación continua para guiar el proceso de aprendizaje; y, de manera significativa, permitir la adaptatividad al ritmo individual del alumno. Como señalan Romero Carbonell et al. (2023), la transformación digital en la educación superior no es solo una cuestión de tecnología, sino que implica "cambios sustanciales y estratégicos en prácticamente todos sus procesos". La tecnología debe ser un medio para mejorar la calidad de la enseñanza y el intercambio de conocimiento, no un fin en sí mismo.

Institucionalmente, la adopción exitosa de un LMS requiere un compromiso organizacional profundo. Esto se traduce en la necesidad de políticas de capacitación docente sólidas, que equipen a los educadores con las competencias digitales necesarias para aprovechar al máximo la plataforma. Asimismo, es vital establecer procesos de evaluación de competencias digitales tanto en docentes como en estudiantes para identificar brechas y ofrecer apoyo. La coordinación con áreas académicas es indispensable para integrar el LMS de manera efectiva en los planes de estudio existentes y asegurar que los contenidos y metodologías se alineen con los objetivos educativos. Socialmente, no se puede ignorar la brecha digital existente entre alumnos urbanos y rurales, así como la necesidad de garantizar un acceso equitativo para todos. La UNESCO (2023)#footnote[UNESCO. (2023). Informe de seguimiento de la educación en el mundo 2023: Tecnología en la educación. UNESCO.] enfatiza que la tecnología educativa tiene el potencial de reducir desigualdades al hacer los contenidos más atractivos y asequibles. Por lo tanto, en el análisis de entornos micro (cada institución y aula) y macro (políticas nacionales, mercado laboral), este sistema LMS interactivo se plantea como un punto de partida fundamental para modernizar la gestión educativa y fomentar una sociedad más equitativa y preparada para el futuro.

#figure(image("../../src/images/esquema-plataforma-lms.jpg", width: 45em), caption: "Esquema de un Sistema de Gestión de Aprendizaje (LMS) y sus usuarios principales.")

#pagebreak()