= Justificación
La presente propuesta de proyecto se justifica en la imperativa necesidad de catalizar la transformación digital en la educación, abordando tanto las promisorias oportunidades que se vislumbran como las significativas amenazas que se presentan como desafío. Los análisis MEFI y EFI realizados previamente han delineado un panorama claro: las tecnologías digitales se han convertido en una necesidad social para garantizar la democratización de la educación como un derecho humano básico, requisito que quedó evidenciado durante la pandemia de COVID-19.

En este sentido, un LMS libre y adaptable puede instalarse en cualquier institución o programa formativo (universitario, técnico o corporativo) sin depender de licencias comerciales costosas. Dado que la brecha digital en el país aún supone retos de acceso, este sistema permitiría ofrecer contenidos educativos a zonas alejadas o con limitados recursos tecnológicos, facilitando la inclusión. Por ejemplo, el Gobierno implementó LMS de código abierto en entidades públicas (como el Seguro Integral de Salud) precisamente por su “sostenibilidad económica”, al eliminar costos recurrentes de licencia#footnote[Implementación de la plataforma de Administración de Aprendizaje Virtual (Learning Management System) en el Seguro Integral de Salud. (s. f.). Programa SISTEC, 2019. https://cdn.www.gob.pe/uploads/document/file/1865048/5199.pdf]. Así, la plataforma propuesta es aplicable tanto en centros de educación superior privadas como públicas, en aulas presenciales o virtuales, y puede ser personalizado a las necesidades locales (idioma, currículo institucional, currícula nacional, etc.), garantizando su despliegue sin restricciones financieras.

== Determinación de Contribución Educativa
Se espera que el LMS planteado pueda contribuir a la modernización y mejora de los procesos pedagógicos y administrativos. Por definición, estas plataformas permiten la creación, gestión y distribución de actividades formativas en línea e integran materiales didácticos con herramientas de comunicación y colaboración. Lo que, a diferencia de la presente propuesta, lo que se espera es poder redefinir el concepto de LMS (Sistema de Gestión de Aprendizaje), al integrar una nueva forma en la cual el centro de todo sea el estudiante y la continua mejora, para el desarrollo de nuevas integraciones pedagógicas y preparación, las cuales puedan derivar de una correcta interpretación del estado académico del estudiante.

De este modo, docentes y estudiantes disponen de un entorno de enseñanza-aprendizaje enriquecido: donde aparte de poder acceder a cursos interactivos, foros, videoconferencias y evaluaciones en cualquier momento y lugar; se podrá aumentar con la capacidad de uso que ofrece la inteligencia artificial tanto para la intuitividad y educación, como revisión de proyectos y definición de providad académica. Estudios realizados por la USMP (Universidad de San Martín de Porres), muestran que el uso de LMS de código abierto (como Moodle) mejora significativamente el aprendizaje colaborativo#footnote[Uso de la Plataforma Moodle para el Desarrollo del Aprendizaje Colaborativo. (2023). USMP - XVI Seminirio Internacional Virtual. https://iced.usmp.edu.pe/ponencias-16/aliaga.pdf] y se alinea con metodologías constructivistas de enseñanza. Además, al ser de acceso libre, el proyecto se vincula con la filosofía de los Recursos Educativos Abiertos; la UNESCO (2024) apoya la innovación digital para “crear vías de aprendizaje a lo largo de toda la vida mejoradas por las TIC”#footnote[Qué necesita saber acerca del aprendizaje digital y la transformación de la educación. (2024). UNESCO, https://www.unesco.org/es/digital-education/need-know.]<UNESCO>.

En conjunto, la integración de estas funcionalidades responden a necesidades educativas concretas: ya que permiten la reducción de la disparidad de recursos entre instituciones, facilitan la actualización continua de contenidos sin la necesidad de integrar a un grupo especializado para una labor que se puede realizar de forma automática, además de que posibilita posibles errores y problemas debido a que la dificultad de gestión es directamente proporcional a la alta cantidad de alumnos inscritos a una sola carrera. Si bien se puede señalar la integración de una metodología que permita el correcto análisis y continuidad del servicio educativo, se debe perspectivar y anteponer sobre todo el seguimiento detallado del desempeño estudiantil, por lo que solo integrando tecnología con multicapacidad y omnipresencia de procesos se optimizará la gestión académica (por ejemplo, automatizando la entrega de certificados o el reporte de calificaciones) y se enriquecerán los procesos didácticos tradicionales con herramientas interactivas, elevando la calidad y relevancia de los aprendizajes.

== Población de Estudio
La población de estudio para la implementación y evaluación de un Sistema de Gestión del Aprendizaje (LMS) de software libre se centrará en dos grupos clave: estudiantes y educadores que actualmente experimentan limitaciones en el acceso a recursos educativos digitales y conectividad, especialmente aquellos ubicados en zonas rurales y de difícil acceso en el contexto peruano. Esta focalización se justifica por la persistente brecha digital que afecta al país, donde, por ejemplo, en 2021, solo 1 de cada 10 estudiantes en zonas rurales tenía conexión a internet y un dispositivo tecnológico (Romero Carbonell, 2023). Aunque el acceso a internet ha aumentado, el 51.8% de la población rural accedió a internet en el último trimestre de 2023, en comparación con el 81.3% en el área urbana (INEI, 2024). Sin embargo, la calidad de la conexión y la posesión de dispositivos adecuados siguen siendo desafíos persistentes (UNICEF, n.d.; Redalyc, n.d.).

En cuanto a la caracterización demográfica, la población estudiantil en Perú, particularmente en el ámbito de la educación superior, abarca un rango de edades que va desde los 18 hasta los 24 años como el segmento predominante, representando un 23.56% de los usuarios de tecnología educativa, seguido por el grupo de 25 a 34 años con un 28.39% (Classter, 2023). Sin embargo, es se debe considerar que la necesidad de alfabetización digital y acceso a recursos educativos se extiende a estudiantes de educación básica regular y de educación básica alternativa, que en 2019 sumaban más de 8 millones de estudiantes (Defensoría del Pueblo, 2021). Para los educadores, la Ley Universitaria Nº 30697 establece una edad máxima de 75 años para el ejercicio de la docencia en universidades públicas (LP, 2017), lo que implica una diversidad de edades y, por ende, de niveles de familiarización con las tecnologías digitales. Investigaciones previas sobre el uso de LMS han identificado que la mayoría de los trabajos se han realizado en el contexto de la educación superior (Dialnet, 2019), pero la necesidad de un LMS de software libre se extiende a cualquier nivel educativo que busque democratizar el acceso al conocimiento.

La selección de la población de estudio se realizará mediante un muestreo no probabilístico por conveniencia o intencional, priorizando instituciones educativas en áreas rurales o con bajo índice de desarrollo digital, o bien, aquellas que expresen una necesidad explícita y disposición para la implementación del LMS. Se buscará obtener una muestra representativa de estudiantes de diferentes niveles educativos (considerando que el LMS puede adaptarse a diversas necesidades) y de docentes de distintas especialidades y edades. La cuantificación de la población se determinará a partir de las cifras de matrícula de las instituciones seleccionadas y del número de docentes activos en las mismas. La evaluación del impacto se centrará en la mejora de las competencias digitales y pedagógicas, la reducción de la brecha de acceso a recursos educativos y la percepción de la calidad educativa, utilizando instrumentos de recolección de datos como cuestionarios, estadísticas anuales realizadas y grupos focales (Dialnet, 2019; Revista Código Científico, n.d.). Esta aproximación permitirá no solo validar la hipótesis sobre el impacto positivo del LMS de software libre, sino también generar recomendaciones sólidas para su escalabilidad y sostenibilidad en el sistema educativo peruano.

== Impacto Esperado del Entorno
Tras el análisis cualitativo mediante la metodología SEPTEL y su posterior cuantificación a través de las matrices MEFI y EFI, esta sección fusiona las ideas corroboradas por la literatura académica con los supuestos derivados del análisis poblacional identificado. El objetivo es armonizar estos resultados para una definición robusta del estudio, fuertemente orientada a la población objetivo y sus beneficios.

- #strong("Población académica y pedagógica: ")Este LMS capacita a los beneficiarios directos en competencias digitales y pedagógicas integrativas. Al utilizar entornos virtuales modernos, docentes y alumnos desarrollarán habilidades tecnológicas en línea con las metas de alfabetización digital de la UNESCO. Esto enriquecerá la experiencia educativa, ofreciendo mayor interacción, flexibilidad y recursos multimedia, y fomentará la inclusión al democratizar el servicio educativo a zonas remotas y personas vulnerables. En suma, los participantes adquirirán mejor formación académica y mayores oportunidades de aprendizaje continuo.

- #strong("Empresas y sector educativo: ")Al ser una solución de software libre, el proyecto generará un mercado de servicios asociado. Empresas de tecnología educativa podrán ofrecer desarrollo, implementación y soporte personalizado de la plataforma, impulsando la industria nacional de TIC y la oferta de capacitación corporativa a bajo costo. Simultáneamente, las instituciones educativas, tanto públicas como privadas, reducirán gastos operativos al eliminar el pago de licencias, permitiendo reorientar esos recursos hacia capacitación o infraestructura. El resultado económico esperado es un ecosistema educativo más dinámico y sostenible.

- #strong("Sociedad orientada a la especialización y aprendizaje: ")Más allá de la población directa, el proyecto busca la democratización del conocimiento, un pilar de la visión de la UNESCO que considera las tecnologías digitales un "bien común" para cumplir con los Objetivos de Desarrollo Sostenible en educación (ODS4). El LMS libre facilitará el intercambio de conocimientos y el acceso abierto a los recursos, contribuyendo al desarrollo social al preparar ciudadanos con mejores competencias educativas y digitales, reduciendo así la brecha entre regiones. Al alinear educación y tecnología, se fortalecerá la competitividad nacional y la inclusión educativa, beneficiando a familias, comunidades y futuros empleadores.

- #strong("Medio Ambiente: ")La implementación del LMS promueve la TI sostenible, minimizando el impacto de las operaciones tecnológicas desde el diseño hasta la disposición final de los equipos (IBM, 2024)#footnote[Ibm. (2024, 30 septiembre). TI sostenible. IBM. https://www.ibm.com/es-es/think/topics/sustainable-it#:~:text=La%20TI%20sostenible%20es%20un,su%20contribuci%C3%B3n%20al%20%206]. Un LMS que funcione en hardware modesto permitirá la reutilización de computadoras antiguas, prolongando su vida útil y reduciendo la generación de residuos electrónicos. Las Tecnologías de la Información y Comunicación (TIC) representan entre el 1.8% y el 3.9% de las emisiones globales de gases de efecto invernadero, y la ONU estima 54 millones de toneladas anuales de residuos electrónicos, de los cuales solo el 20% se recicla. Como se mencionó en el análisis ambiental del SEPTEL, migrar actividades educativas al entorno virtual disminuirá la necesidad de traslados físicos y la impresión de materiales, mitigando así las emisiones de carbono y el consumo de papel. Sin embargo, es importante reconocer la necesidad de reorientar carreras con uso de laboratorio presencial y fomentar la autoeducación con responsabilidad. El objetivo es que la calidad educativa virtual sea comparable a la presencial, ofreciendo a las instituciones de educación superior la flexibilidad de ser centros de aprendizaje adaptados a las necesidades de los estudiantes.

== Beneficiarios Directos e Indirectos
La implementación de un LMS de software libre genera un entramado de beneficios que se extienden más allá de los usuarios inmediatos, permeando diversas capas de la sociedad. Por lo que, si bien se ha defindio el entorno al que se orienta la propuesta, en esta instancia se pretender radicar en profundidad sobre quiénes son los receptores específicos de estos impactos, y cómo la naturaleza del software libre potencia una distribución más equitativa de las ventajas. Este enfoque especializado permite discernir los mecanismos precisos por los cuales se materializan las mejoras.

- #strong("Beneficiarios Directos: ")Roles internos que interactuarán activamente con la plataforma y verán una mejora tangible en sus roles y capacidades:
  
  - #strong("Estudiantes: ")Serán los usuarios finales de la plataforma, accediendo a recursos de aprendizaje diversificados y a oportunidades de interacción asíncrona y síncrona. La ventaja específica para ellos es la adquisición de competencias digitales prácticas a través del uso cotidiano del LMS, lo que los preparará directamente para entornos laborales y académicos crecientemente digitalizados (UNESCO, 2018). Esto se diferencia de un impacto general en "alfabetización digital" al enfocarse en la experiencia operativa y la formación de habilidades concretas.

  - #strong("Docentes y Tutores: ")Optimizarán sus metodologías de enseñanza-aprendizaje. El LMS les proporcionará herramientas para la gestión eficiente de cursos, la personalización del contenido educativo y la evaluación formativa detallada, liberando tiempo para una mayor dedicación a la interacción pedagógica y la retroalimentación individualizada. Esto va más allá de un "desarrollo de habilidades pedagógicas integrativas" al especificar la aplicación funcional de la plataforma en su labor diaria.

  - #strong("Personal Administrativo y de Gestión Académica: ")Experimentarán una racionalización y automatización de procesos como la gestión de matrículas, seguimiento de expedientes, comunicación institucional y generación de reportes. El beneficio clave es el aumento de la eficiencia operativa y la reducción de la carga de trabajo manual, lo que permite una asignación más estratégica de recursos humanos.

  - #strong("Equipos de TI Institucionales (Desarrolladores y Administradores): ")Estos profesionales capitalizarán la experiencia en la implementación, configuración y mantenimiento de un sistema robusto de código abierto. Su beneficio radica en el desarrollo de capacidades técnicas especializadas en un stack tecnológico flexible, y la posibilidad de contribuir con parches o mejoras a la comunidad global de software libre, potenciando su perfil profesional y el reconocimiento institucional.

- #strong("Beneficiarios Indirectos: ")Roles externos que experimentarán mejoras como resultado de la expansión del acceso y la calidad educativa, sin interactuar directamente con la plataforma:

  - #strong("Familias de Estudiantes y Comunidades Locales: ")Se beneficiarán por la disminución de barreras geográficas y económicas al acceso educativo, lo que puede traducirse en una mejora del capital humano local y en una mayor movilidad social a largo plazo. La presencia de estudiantes más capacitados puede inspirar a otros miembros de la comunidad, fomentando un entorno de aprendizaje continuo.

  - #strong("Empresas del Sector EdTech y TIC (Nacional y Regional): ")Este proyecto estimulará un mercado de servicios especializados en torno a un LMS de código abierto. Esto significa oportunidades de negocio para consultoría, desarrollo de módulos personalizados, soporte técnico, capacitación y hosting. El beneficio es la creación de un nuevo nicho de mercado y el fortalecimiento del ecosistema tecnológico local, impulsando la innovación y la generación de empleo cualificado.

  - #strong("Organismos Gubernamentales y Formuladores de Políticas Educativas: ")Obtendrán un modelo validado de implementación de tecnología educativa de bajo costo y alto impacto, que puede ser replicado a escala nacional. El beneficio directo es disponer de una herramienta para avanzar en las metas de inclusión digital y calidad educativa, ofreciendo datos para la toma de decisiones y la formulación de políticas públicas más efectivas y sostenibles.

  - #strong("Sociedad Peruana Adulta: ")Se beneficiará de una mayor equidad educativa y una fuerza laboral más capacitada digitalmente. Esto contribuye a la reducción de brechas socioeconómicas y a un mayor desarrollo del país, facilitando la participación ciudadana en la economía del conocimiento y fortaleciendo la competitividad global a través de la formación de ciudadanos con mejores competencias.

== Proyección Estratégica
La implementación de este proyecto se cimienta en la urgencia de una acción estratégica y proactiva, trascendiendo la mera integración tecnológica. Nuestro enfoque radica en un despliegue equitativo, sostenible y de alto impacto. Específicamente, el proyecto aspira a:

- Reducir la brecha educativa digital en la región y el país, garantizando que la tecnología actúe como un puente facilitador y no como una barrera restrictiva.

- Mejorar la calidad y relevancia de la educación, equipando a los estudiantes con las habilidades esenciales para afrontar los desafíos y oportunidades del futuro.

- Promover un uso ético y seguro de la tecnología, fomentando la confianza en los ecosistemas educativos digitales.

- Fomentar la sostenibilidad ambiental en cada fase, desde la implementación hasta la operación de la infraestructura digital.

En conjunto, este proyecto busca asegurar que la transformación digital en la educación se traduzca en una mejora significativa en el acceso y la democratización del conocimiento, en consonancia con el Objetivo de Desarrollo Sostenible 4 (ODS4) de la UNESCO. Este LMS se concebirá como un sistema resiliente, inclusivo y adaptado a los desafíos y oportunidades tecnológicas que emergen de la Web 4.0, permitiendo así ofrecer una educación de mayor calidad y con garantías optimizadas para el estudiante en el siglo XXI.

#pagebreak()