= Objetivos


== Objetivo General
Diseñar e implementar un Sistema de Gestión del Aprendizaje (LMS) de software libre que democratice el acceso educativo y fortalezca las competencias digitales para optimizar la dinámica del proceso de enseñanza-aprendizaje en el ámbito superior y especializado.

== Objetivos Específicos
Para alcanzar el objetivo general, se han definido cinco objetivos específicos, formulados bajo los criterios SMART y alineados con el cronograma establecido del 1 al 30 de junio. Cada objetivo delinean el "cómo" se logrará el propósito principal y aportará al rigor metodológico del estudio.

1. #strong("PRIMERO: ")Diagnosticar, durante la primera semana de desarrollo (del 1 al 7 de junio), el estado actual de la infraestructura tecnológica, los sistemas de gestión de información existentes y las competencias digitales de estudiantes y docentes en las instituciones de educación superior y especializada participantes, mediante la administración de encuestas estructuradas a una muestra representativa de ambos grupos (al menos 150 estudiantes y 30 docentes), la revisión de documentación institucional sobre recursos tecnológicos y la realización de grupos focales con el personal de TI, para que los resultados se sistematicen y así obtener una caracterización detallada de las condiciones de partida y las brechas digitales actuales, permitiendo identificar puntos clave para el desarrollo de los requerimientos del sistema.

2. #strong("SEGUNDO: ")Identificar y documentar, hasta la segunda semana de desarrollo (del 8 al 14 de junio), los requisitos funcionales y no funcionales detallados para el LMS de software libre, priorizando aquellos que optimicen la interacción pedagógica, la personalización del aprendizaje y la adaptabilidad a contextos de conectividad variada, mediante la revisión exhaustiva de mejores prácticas en LMS de código abierto enfocados en entornos con recursos limitados, lo que resultará en un documento de requisitos detallado que servirá como base fundamental para el diseño posterior.

3. #strong("TERCERO: ")Diseñar, durante la tercera semana de desarrollo (del 15 al 21 de junio), la arquitectura modular y los componentes clave de un prototipo funcional del LMS de software libre, garantizando su escalabilidad, facilidad de mantenimiento y cumplimiento con los principios de diseño centrado en el usuario (UCD), mediante la elaboración de diagramas de arquitectura (ej. UML), especificaciones técnicas de los módulos principales (gestión de usuarios, cursos, contenidos, evaluaciones) y prototipos de interfaz de usuario (mockups o wireframes); evaluendo el cumplimiento de los estándares de diseño y la fluidez de la interacción a través pruebas de usabilidad iniciales con al menos 5 usuarios representativos.

4. #strong("CUARTO: ")mplementar, durante la cuarta semana de desarrollo (del 22 al 28 de junio), un prototipo funcional del LMS de software libre en un entorno de prueba controlado, asegurando la operatividad del 80% de sus funcionalidades críticas y la compatibilidad con dispositivos de bajo costo, mediante el desarrollo de los módulos principales identificados en el diseño, utilizando tecnologías de código abierto (ej. Java/SpringBoot, TypeScript/Angular, PostgreSQL) y su despliegue en un servidor de pruebas; la operatividad se medirá a través de pruebas unitarias y de integración, confirmando que al menos el 80% de las funcionalidades clave (creación de cursos, carga de recursos, acceso de usuarios, entrega de tareas) funcionan correctamente, y la compatibilidad se evaluará en al menos 5 dispositivos de gama media/baja.

5. #strong("QUINTO: ")Evaluar, antes de la semana final de entrega (antes del 30 de junio), el desempeño técnico, la usabilidad y la percepción de valor del prototipo del LMS, cuantificando su impacto inicial en la mejora de las competencias digitales de los usuarios y en la optimización de la dinámica del proceso educativo superior y especializado, mediante la aplicación de cuestionarios de usabilidad (ej. SUS) a un grupo piloto de al menos 10 usuarios (estudiantes), la recolección de métricas de rendimiento (ej. tiempo de carga, errores del sistema) y la realización de grupos focales para obtener retroalimentación cualitativa sobre la experiencia de aprendizaje y la percepción de la optimización del proceso educativo, permitiendo identificar áreas de mejora y validar la pertinencia del prototipo.

#pagebreak()