= Propuesta y Metodología
En esta etapa, se busca definir los procesos operativos clave dentro de una institución educativa que ofrece modalidades de enseñanza virtual, presencial y semipresencial. Estos procesos se enmarcan en lo que se conoce como Planificación Educativa Administrativa (AEP)#footnote[AEP (Administrative Educational Planning): En este contexto específico, AEP se refiere a la Planificación Educativa Administrativa, un enfoque para la organización y sistematización de los recursos, el personal y los procesos dentro de una institución educativa con el fin de optimizar la gestión y asegurar la calidad y continuidad del servicio de enseñanza-aprendizaje.].

La Planificación Educativa Administrativa (AEP), como concepto fundamental en la gestión de instituciones educativas, abarca la organización y sistematización de los recursos y el personal para asegurar la continuidad y calidad del servicio. Como señala Vega (2011), la planificación en la administración educativa es crucial para la eficiencia y el logro de objetivos. En este sentido, los modelos educativos administrativos derivados de una sólida AEP permiten la correcta organización del personal, la gestión eficaz de los recursos, la definición clara de las responsabilidades y, fundamentalmente, la resolución eficiente de conflictos relacionados con los contenidos.

Estos recursos incluyen tanto el capital humano, es decir, docentes y administradores de aprendizaje, quienes son pilares en la entrega del servicio educativo, como la población estudiantil. Los alumnos, como usuarios principales que invierten en el servicio educativo, esperan una continuidad sin interrupciones y una adaptabilidad que les permita ajustar su tiempo y horarios con la asignación deseada de cursos. La fluidez en estos procesos es directamente proporcional a la satisfacción y retención del estudiante.

Si bien docentes y administradores son puntos clave en la operación central, el éxito y la expansión de este complejo proceso dependen de la interacción con otros actores y niveles de gestión. Organismos de apoyo, como los equipos de soporte técnico (*Help Desk*), son esenciales para resolver problemas y garantizar la operatividad continua de la infraestructura tecnológica. Asimismo, la Junta Directiva, que establece las políticas, las reglas de cumplimiento y la aprobación de planes de estudio, junto con las subdirectivas que aseguran la continuidad del servicio, operan en círculos de acción que pueden extenderse a un tercer o incluso cuarto nivel de influencia.

Por lo tanto, aunque el presente desarrollo no se enfocará directamente en la infraestructura y el diseño detallado del servicio (los cuales se encontrarán disponibles en el manual de diseño del proyecto), es imprescindible comprender que la correcta gestión del aprendizaje, cuya eficacia se refleja directamente en la operatividad de la plataforma educativa utilizada (como Blackboard), puede describirse y optimizarse eficientemente. Esto se logra a través del uso de una metodología de modelado de procesos de negocio (BPM)#footnote[BPMN (Business Process Model and Notation): Es una notación gráfica estándar utilizada para modelar y representar flujos de procesos de negocio de manera clara y comprensible, tanto para expertos técnicos como para usuarios de negocio. Su objetivo es facilitar el diseño, análisis, ejecución y monitoreo de procesos.].

BPM proporciona las herramientas y el marco necesarios para visualizar, analizar y mejorar estos flujos de trabajo administrativos y educativos, sentando las bases para una gestión más eficiente y, en su etapa inicial, reactiva. Tras este análisis de procesos, se determinará también la aplicación de la notación DMN#footnote[DMN (Decision Model and Notation): Es una notación estándar y un marco de modelado para representar y automatizar la lógica de las decisiones. Permite definir de manera precisa y ejecutable cómo se toman las decisiones en un proceso de negocio, facilitando su análisis, gestión y automatización.] para formalizar la lógica de las decisiones que se toman en cada paso del proceso, asegurando la continuidad educativa y la coherencia en las operaciones.

== Metodología de Gestión Educativa Superior
La sistematización de un plan educativo administrativo es fundamental para adaptar modelos educativos a un entorno de aprendizaje mediado por plataformas tecnológicas. Es decir, estos modelos deben estar intrínsecamente alineados con el servicio que las instituciones educativas adquieren y ofrecen en entornos virtuales, presenciales y semipresenciales, caracterizados por su alto alcance y la demanda actual de flexibilidad. En este sentido, los modelos educativos no solo se sustentan en una base de recursos, sino que exigen una gestión optimizada de los mismos para su puesta en práctica efectiva.

Cada modelo educativo posee su propio contenido y estructura pedagógica, lo que implica que la institución debe asegurar el desarrollo de las habilidades y competencias propuestas en su plan curricular. Por consiguiente, los modelos educativos más exitosos y pertinentes en el panorama actual son aquellos intrínsecamente adaptativos y flexibles, capaces de responder a las necesidades cambiantes del estudiantado y del mercado laboral#footnote[Impulso. (2024, 12 septiembre). Diseño Universal para el Aprendizaje: El Arma Secreta del Profe 3.0. Impulso06. https://impulso06.com/diseno-universal-para-el-aprendizaje-el-arma-secreta-del-profe-3-0/].

El plan educativo administrativo define el marco temporal y estratégico dentro del cual los órganos directivos y de gestión (como las juntas y direcciones de área) colaboran para diseñar e implementar modelos curriculares que se adapten a la planificación anual. Un objetivo clave de esta colaboración es la constante actualización de contenidos de carrera, buscando no solo la relevancia académica, sino también la motivación del estudiantado mediante el desarrollo de competencias alineadas con las demandas contemporáneas.

No obstante, es pertinente señalar que existen diferencias significativas en la agilidad para el cambio curricular entre instituciones técnicas especializadas y universidades. Esta capacidad de adaptación suele ser inversamente proporcional al tamaño de la población estudiantil y a la rigidez de los planes de estudio, así como a la disponibilidad y perfil del cuerpo docente. Mientras que las instituciones técnicas pueden ajustar con mayor celeridad sus programas para responder a necesidades específicas de la industria, las universidades, con estructuras más amplias y currículos fundamentales de mayor estabilidad, enfrentan inconsistencias en la implementación de cambios anuales sustanciales#footnote[Perez, M. (2025, 12 mayo). SCORM: qué es e importancia en el e-learning. SMOWL Proctoring | Sistema de supervisión para exámenes online. https://smowl.net/es/blog/scorm-que-es-e-importancia/]. Es necesario reconocer que la flexibilidad curricular es un proceso complejo que abarca desde la normativa administrativa hasta las metodologías pedagógicas.

Adicionalmente, las instituciones disponen de personal capaz de cumplir funciones de gestión y resolución de incidencias. Estos roles, a menudo englobados bajo el término de administradores de LMS o especialistas en gestión académica, son responsables de resolver colisiones o problemas que surgen entre diferentes módulos educativos o en la asignación de recursos. Su labor es la de asegurar la continuidad educativa (isEazy, 2024). Complementariamente, la función de profesores y maestros es primordial en la adaptación de los modelos educativos propuestos, para lo cual se les proporciona el material técnico y pedagógico necesario para facilitar la revisión teórica y la aplicación práctica en el aula, buscando la comprensión por parte del estudiante.

#figure(
  image("../../src/images/Esquema Conceptual AEP.png"),
  caption: " Esquema conceptual de la Planificación Educativa Administrativa (AEP)"
)

El diagrama proporcionado, representa una vista de alto nivel de las interacciones y elementos fundamentales que rigen la gestión académica. En esta representación, la "zona de educación", entendida como el entorno o el ámbito donde se imparte y recibe la enseñanza, se constituye como una parte intrínseca del plan educativo general. Su configuración responde a la necesidad de alinear la influencia del proceso educativo y la organización de los materiales con las tendencias y demandas del alumnado.

Por otra parte, las "colecciones de cursos" se conceptualizan como las entidades educativas de apoyo fundamentales dentro de cada modelo de educación. Estas colecciones no operan de forma aislada; por el contrario, se conciben para intercambiar información y recursos entre sí, permitiendo así una selección más flexible y dinámica en la configuración de itinerarios formativos o la adaptación a diferentes perfiles de estudiantes.

De esta manera, para dinamizar y asegurar una correcta Planificación Educativa Administrativa (AEP), es imperativo considerar y gestionar eficientemente los siguientes parámetros relacionados con las colecciones de cursos, tal como se deriva del análisis de los procesos subyacentes:

- #strong("Descripción del Componente Sistemático Educativo: ")Este parámetro se refiere a la necesidad de detallar y documentar las características estructurales y metodológicas de cada elemento dentro del sistema educativo. Incluye la definición de objetivos de aprendizaje, metodologías de enseñanza, estrategias de evaluación y los prerrequisitos o habilidades esperadas para cada curso o módulo. Una descripción clara es fundamental para la coherencia curricular y la comprensión por parte de todos los stakeholders.

- #strong("El Número de Capacitaciones / Formaciones: ")Este parámetro cuantifica la oferta formativa disponible, ya sea en términos de cursos completos, módulos específicos o unidades de capacitación. Su gestión adecuada permite planificar la carga académica, optimizar la asignación de recursos docentes y asegurar que la oferta responda a la demanda y a los objetivos estratégicos de la institución.

- #strong("El Número de Puntuaciones Ofrecidas (Créditos / Evaluaciones): ")Este punto alude a la métrica de valoración académica asociada a cada componente del curso. Esto puede referirse a la cantidad de créditos académicos que otorga un curso, el número de evaluaciones significativas que contribuyen a la calificación final, o la ponderación de estas. Una definición precisa es crucial para la transparencia en el progreso del estudiante y la validez de los títulos.

- #strong("Recuento y Justificación de Puntuaciones por Colección de Cursos: ")Más allá de las puntuaciones individuales, es necesario un recuento consolidado y una justificación de cómo estas puntuaciones (o créditos/evaluaciones) se distribuyen y se suman dentro de las colecciones de cursos y el modelo educativo general. Esto es esencial para la acreditación de programas, la verificación del cumplimiento de los requisitos curriculares y la justificación de la carga académica total frente a los estándares educativos y los requerimientos del estudiante. Permite validar que los objetivos de aprendizaje se están cubriendo de manera adecuada.

Es importante señalar que la gestión de estos parámetros y la articulación de las colecciones de cursos son responsabilidades clave de los directores de departamento. Son ellos quienes, con su conocimiento especializado de las disciplinas y los requisitos académicos, aseguran que las colecciones de cursos se completen y se mantengan actualizadas dentro del marco del modelo educativo establecido por la Planificación Educativa Administrativa.

#figure(
  image("../../src/images/Estados del AEP.png"),
  caption: "Estados de Gestión de Planes de Estudio (AEP)"
)

Para complementar la vista conceptual del diagrama y los parámetros de las colecciones de cursos, es necesario entender los procesos de negocio específicos que sustentan la Planificación Educativa Administrativa (AEP). En el sistema actual, durante la fase de modelado de la educación, se planifican los roles de profesores y estudiantes, así como los recursos técnicos y materiales (MTR), con el fin de determinar los parámetros que respaldarán el modelo educativo en el proceso general de enseñanza.

Los siguientes procesos de negocio se implementan bajo esta categoría de AEP, y se reflejan en el flujo de gestión de Planes de Estudios:

1. #strong("Estructuración y Gestión de Horarios: ")Este proceso se enfoca en la creación de un cronograma detallado para el modelo educativo. Implica la determinación de los periodos de estudio y los días no lectivos, así como la cantidad de cursos de capacitación diarios y su duración a lo largo del día. 

2. #strong("Identificación y Operación de Modelos Educativos: ")Consiste en la identificación y registro de los modelos educativos dentro de la Planificación Educativa Administrativa, siendo un paso esencial para la operacionalización de cada modelo y puestos luego a disposición para su posterior evaluación.

3. #strong("Agrupación de Recursos y Verificación de Oportunidades:  ")Este proceso implica agrupar los cursos, los estudiantes y los recursos materiales técnicos necesarios para cada oferta educativa. Se verifica la viabilidad de impartir la capacitación en función de la información horaria y la disponibilidad de recursos.

4. #strong("Organización de la AEP a Nivel de Facultad y Gestión de Conflictos: ")Se busca establecer una Planificación Educativa Administrativa coherente y funcional dentro de cada facultad. Esto incluye la gestión y resolución de posibles colisiones entre estudiantes y profesores. Las demandas relacionadas con los recursos de los modelos educativos se recopilan y se envían a un despachador central de manera periódica (ej., una vez al mes).

5. #strong("Coordinación y Diseño de Órdenes Educativas a Nivel Superior: ")Este proceso implica la necesidad de compartir recursos generales entre Establecimientos de Educación Superior y verificar la proporcionalidad de las unidades de Planificación Educativa Administrativa entre diferentes facultades (ej., en relación con los horarios mensuales). Adicionalmente, se verifican las asignaciones de profesores, la población estudiantil y la disponibilidad de MTR. En este sistema, se diseñan órdenes generales para los encuentros educativos. Los procesos educativos de la AEP inician con su propio esquema y confirmación, y en la siguiente etapa, se determina la lista de módulos de planificación educativa para su implementación práctica.

Por otra parte, el proceso de organización de la Planificación Educativa Administrativa se subdivide en dos procesos de negocio principales: Proyecto y Formación. El objetivo del proceso de Proyecto es determinar la suma total de módulos que se implementarán dentro de esta Planificación Educativa Administrativa. Por otro lado, el proceso de Formación busca combinar a los estudiantes y profesores con los módulos de planificación educativa definidos.

Tras esto, una vez que el gráfico del proceso educativo ha sido estructurado por el responsable del modelo educativo, este genera una serie de requisitos para el Módulo de Planificación Educativa. Estas demandas incluyen:

- La especificación de las colecciones de cursos que deben ser completadas.

- La fecha de presentación de la primera versión de las colecciones de cursos completadas.

- La fecha de operación de la última versión de las colecciones de cursos completadas.

Los propietarios del Módulo de Planificación Educativa son los encargados de poblar las colecciones de cursos con los módulos educativos, basándose en las demandas previamente mencionadas. Existe la flexibilidad de utilizar módulos de planificación educativa ya existentes en otras colecciones educativas para archivar nuevas colecciones de cursos, optimizando así la reutilización de recursos.

== Análisis de Procesos de Negocio
Para desarrollar el presente análisis, es fundamental enfatizar la comprensión de los procesos de negocio que sustentan la Planificación Educativa Administrativa (AEP) en las instituciones de nivel superior. Resulta crucial comprender la secuencia de actividades, las responsabilidades de los actores y los flujos de información que caracterizan la operación académica y administrativa. Mediante la aplicación de la metodología de modelado de procesos de negocio (BPMN), se logra representar visualmente el ciclo de vida de la AEP, desde la definición estratégica hasta la ejecución operativa. A diferencia de lo establecido anteriormente respecto al uso exclusivo de diagramas y modelos de estados, la integración de una perspectiva procedimental basada en tareas y subprocesos permite definir con mayor precisión el funcionamiento central de los procesos a optimizar. De esta forma, la interacción posterior, en relación con la entrega del proyecto de software, estará más alineada con las necesidades empresariales reales. 

#figure(
  image("../../src/images/Proceso de Gestión de la Planificación Educativa.png"),
  caption: "Proceso de Gestión de la Planificación Educativa Administrativa (AEP) - Nivel General"
)

El diagrama presentado pretende ilustrar una visión de alto nivel del Proceso de Gestión de la Planificación Educativa Administrativa (AEP) dentro de una institución de educación superior. Este modelo general, diseñado bajo la notación BPMN (Business Process Model and Notation), busca ofrecer una representación clara y estandarizada de las interacciones clave entre los diferentes niveles organizacionales y las principales etapas que garantizan la continuidad y calidad del servicio educativo.

El diagrama se organiza en tres carriles horizontales, que representan los principales niveles de responsabilidad y autoridad dentro de una institución educativa, según la jerarquía funcional y la naturaleza de sus tareas:

- *Nivel Estratégico:* Este carril engloba a los órganos de gobierno y alta dirección (como la Junta Directiva) responsables de la formulación de la visión, misión y políticas generales de la institución. Sus actividades son de carácter normativo y definen el marco macro en el cual operarán los demás niveles. En el contexto de la AEP, este nivel sienta las bases para el desarrollo curricular y administrativo, asegurando la alineación con los objetivos institucionales a largo plazo (Whetten, 2017).

- *Nivel de Gestión:* Este carril agrupa a las direcciones de área, los responsables de modelos educativos, administradores de AEP y propietarios de módulos de planificación educativa. Su rol es traducir las directrices estratégicas en planes operativos concretos, coordinar recursos, supervisar la implementación y resolver conflictos a un nivel táctico. Este nivel armoniza la articulación de la visión y la ejecución, garantizando que los recursos y procesos estén optimizados para la entrega del servicio (Mintzberg, 1980).

- *Nivel Operativo:* Este carril representa a los actores directamente involucrados en la entrega del servicio educativo y en la interacción final con el estudiante, incluyendo docentes, el Help Desk/soporte técnico y, fundamentalmente, los estudiantes como beneficiarios del proceso. Las actividades en este carril son de ejecución directa y muestran la experiencia real del aprendizaje y la interacción con la infraestructura educativa.

Por otra parte, podemos mencionar que el proceso se inicia con un evento y progresa a través de una secuencia lógica de tareas y subprocesos, cada uno representando un conjunto de actividades interrelacionadas.

De esta manera, podemos resaltar que, tras el inicio de la decisión de la planificación anual del AEP, la Junta Directiva o los órganos directivos superiores definen y aprueban las políticas generales que guiarán el diseño y la implementación de los planes de estudio y la operación educativa. Tras la cual, se obtiene un documento o conjunto de directrices para establecer el siguiente nivel de gestión. Consecuentemente, de forma secuenciada se establece una junta para poder definir la planificación de roles, los cuales, se espera consideren la adquisición de recursos técnicos y materiales (MTR), además de la generación de requisitos específicos para la planificación educativa. Tras obtener un resultado consolidado de diseño; los modelos educativos con su estructura pedagógica y administrativa definida, establecen apertura para dar paso a la parte operativa del proceso, pero no sin antes establecer otra cadena de subprocesos de los cuales se planea la gestión operativa de planes AEP.

Estando en este punto, este subproceso contiene procesos de negocios relacionados con la conversión de los modelos planificados en planes ejecutables. De esta forma, se pretende el desarrollo de una estructuración y gestión de horarios, la identificación y operación de los modelos educativos, la agrupación y verificación de recursos (con la posible inclusión de decisiones de viabilidad), la organización de la AEP a nivel facultad y la coordinación a nivel superior. Además, cabe resaltar que en este subproceso ocurre la asignación de docentes y estudiantes, tratando de resolver las colisiones preliminares. Como salida, podemos señalar que se espera que la definición de los planes que pasaron por las diversas fases de viabilidad, asignación de recursos y resolución de conflictos iniciales, estén listos para ser implementados en la práctica.

Continuando, la tarea continua operativa, pretende como principal objetivo garantizar que el servicio educativo se mantenga sin interrupciones significativas. De esta manera, lo que se pretende es que los operarios de esta sección de actividad ejerzan un papel que incluye la resolución de colisiones o problemas que surgen entre diferentes módulos o en la asignación de recursos ya en fase de ejecución. Cabe resaltar que en este nivel se puede dar de manera reactiva ante posibles problemas o solicitudes de soporte provenientes de círculos más altos o directos, como puede ser con los usuarios finales (docentes y estudiantes). De esta manera, resulta necesario que exista una confirmación de la no existencia de impedimentos críticos para la entrega del servicio educativo, o que los existentes han sido gestionados, permitiendo así el avance a nivel de operación directa.

Tras el aseguramiento de la continuidad operativa, las actividades directas de enseñanza-aprendizaje se encapsulan en un subproceso, el cual incluirá las tareas de los docentes para adaptar los modelos educativos y el material pedagógico para la entrega en el aula (virtual, presencial, semipresencial), la participación activa de los estudiantes en el proceso formativo, y la función de soporte técnico (*Help Desk*) para resolver problemas de infraestructura tecnológica que puedan surgir durante la ejecución de los recursos dentro de la plataforma de aprendizaje. Esto permitirá materializar la continuidad educativa del AEP al estudiante.

=== Análisis del Subproceso de Diseño de Modelos Educativos
Partiendo con la práctica de la adaptación del modelo a partir del curso llevado, se puede mencionar que este primer proceso, como se mencionó anteriormente, constituye la fase inicial y fundamental de la AEP (a nivel táctico). Si bien se mencionó que en este proceso es el punto donde las directrices estratégicas de la institución se transforman en una estructura pedagógica y administrativa viable y operativa; cabe enfatizar que este proceso no es meramente una formalidad, sino un acto de ingeniería curricular y organizativa que define la calidad, pertinencia y eficiencia de la oferta académica (Tuning Educational Structures in Europe, 2005)#footnote[Tuning Educational Structures in Europe. (2005). Reference Points for the Design and Delivery of Degree Programmes in 30 Subject Areas. Publicaciones de la Universidad de Deusto.].

Si bien, desarrollando más este subproceso, se puede definir correctamente su inicio por parte de una iniciativa de la "Dirección Académica/Curricular". Su primer insumo, siendo el "Marco Estratégico AEP Definido", proviene directamente del Nivel Estratégico superior. Muchas instituciones actuales, si bien no cuentan con un desarrollo tan específico de etapas de procesos, se puede inferir a través de diversas fuentes académicas que la estandarización de este marco de trabajo establece la necesidad propia de establecer una correcta interconexión del "Marco Estratégico Definido (AEP)" con la gobernanza educativa sólida que se pretende brindar, junto con una alineación estratégica como precondición para cualquier diseño curricular (García-Peñalvo et al., 2020). Por lo que, inherentemente, la tarea subsecuente se basa en la pertinencia de un análisis crítico por parte de la junta, en el cual, según expertos en gestión educativa, debe dar como resultado la interpretación y contextualización de las políticas generales, como la misión institucional, los valores educativos y las prioridades de desarrollo a largo plazo. Puntos los cuales se adhieren directamente a una metodología en particular, además de una modalidad de educación.

Por lo tanto, la definición y alineación de indicios de probidad académica inherente a las reglas institucionales establecidas por instituciones gubernamentales de evaluación educacional, tanto nacional como privada, busca la integración continua de nuevos reglamentos, como puede ser el más reciente para una modalidad a distancia como normativas de evaluación supervisada o normativas de probidad de revisión de plagio directo de inteligencia artificial. Por lo que, la omisión o deficiencia en esta fase puede derivar en la creación de modelos educativos desvinculados de la visión institucional, el incumplimiento de normativas nacionales educativas, ineficiencias académicas y conflictos en etapas posteriores, debido a la posible obligación de cambio que se deba hacer tras la corrección por la falta de cumplimiento institucional ante normativas educativas públicas.

#figure(
  image("../../src/images/Subproceso-Diseño de Modelos Educativos.png"),
  caption: "Subproceso de Diseño de Modelos Educativos. Nota. Elaboración propia."
)

Como se pudo observar, antes de la concepción curricular, el proceso demanda una rigurosa contextualización. Por lo que, la consulta a la base de datos determinada para la generación de documentos de requisitos y acreditación son pasos ineludibles que garantizan que el modelo propuesto cumpla con las normativas educativas nacionales e internacionales, así como los estándares de calidad exigidos por agencias acreditadoras (Stella & Convergence, 2006). Paralelamente, el estudio de tendencias del mercado laboral, por parte de analistas de necesidades académicas, busca la pertinencia económica del modelo educativo. En un entorno globalizado y de rápida evolución, la empleabilidad de los egresados y la capacitación de la institución para responder a las necesidades de la sociedad son factores que determinan el éxito y sostenibilidad del modelo educativo a seguir; de esta manera el reporte de tendencias y demandas se convierte en un insumo vital para la innovación y la relevancia curricular.

En continuación, la toma de decisiones posteriores se basa a partir de la definición de alcance y objetivos a perseguir del modelo a seguir; por lo que se debe enfatizar en lograr sentar las bases para una toma de decisión crítica de actualización o creación de un nuevo modelo, siendo que la evaluación de recursos, un análisis de obsolescencia curricular y una proyección del impacto, son subtareas que se deben realizar en esta etapa para definir el seguimiento de una estrategia incremental o disruptiva en la oferta académica (Christensen, 2011).

Consecutivamente, el núcleo del diseño reside en la iniciación del diseño modélico educativo, el cual, simultáneamente debe activar tres frentes de trabajo, debido a la complejidad interdisciplinaria que puede abarcar el seguir un modelo educativo:

-   *Diseño Curricular Pedagógico Detallado*, en el cual se debe establecer la estructura epistemológica y didáctica del modelo; en el cual se definen los objetivos de aprendizaje (basados en competencias), las metodologías de enseñanza-aprendizaje, las estrategias de evaluación y los prerrequisitos de cada curso o módulo.

-   *Identificación de Requisitos de Materiales Técnicos y Recursos (MTR)*, en el cual se aborda la viabilidad tecnológica y de infraestructura del modelo, teniendo que buscar la viabilidad de uso de plataformas especializadas que estén sujetas en armonía con recursos presenciales, *hardware* y otros técnicos; dado que mencionamos la forma en que muchas organizaciones que brindan educación especializada buscan el uso de una plataforma, es en este punto, en el que la enseñanza es inoperable, si no se establecen recursos adecuados.

-   *Definición de Roles y Perfiles Requeridos y Viabilidad Docente*, en un aspecto de gestión de talento humano, en el cual se verifica la disponibilidad y definición de las necesidades de capacitación docente o de nuevas contrataciones. En este punto la flexibilidad curricular a menudo choca con la disponibilidad y especialización del cuerpo docente, como se señala en el texto introductorio, haciendo de esta una decisión mutua (entre docentes y junta o encargados de recursos humanos), en el cual puede desembocar en una operación compleja.

Si bien, subsecuentemente, se puede mencionar que en este punto, se debería dar paso a una elevación de aprobación por junta (nivel estratégico), se puede detallar el paso final, que implica la incorporación oficial a la oferta institucional y su preparación para la operacionalidad; lo que en términos, se daría si la aceptación por parte de junta fuera favorable, por otro lado, se esperaría una iteratividad en procesos anteriores en el ámbito del desarrollo curricular, el cual, la definición total de este paso bifurcado, determinará el retraso en la definición de requisitos de población de recursos en base a un modelo educativo o una reestructuración tanto conceptual como de implementación práctica. Asegurando siempre que este subproceso busque la correcta planificación administrativa basada en coherencia y ejecución.

=== Análisis del Subproceso de Gestión Operativa de Planes de AEP
A nivel de gestión, los modelos educativos diseñados se transforman en una oferta académica concreta y operacionalmente viable. Por lo que, la articulación entre el diseño conceptual y la implementación práctica, asegura que cada plan educativo cuente con los recursos (humanos, técnicos y de infraestructura) y la estructura temporal necesarios para su ejecución (Tuning Educational Structures in Europe, 2005). De esta manera, la eficiencia operativa presente en este proceso ayudará a la definición de la satisfacción de los grupos de interés, en los cuales podemos mencionar tanto los estudiantes como el personal docente y administrativo. Si bien puede resultar en un seguimiento complejo y continuo, actualmente, muchos de estos procesos se delegan de forma automatizada, dada la alta cantidad de ofertas académicas que se tienen y de esta manera cómo se tiene que aplicar un modelo educativo específico por facultad. En ese sentido, la interacción del actor tecnológico (Sistema de Gestión, mayormente LMS) define la forma en cómo debe centrarse en brindar la correcta información que se tiene tanto en forma de informe de acta, como en la continuidad de esta e interacción directa con el sistema.

#figure(
  image("../../src/images/Subproceso-Gestión Operativa de Planes de AEP.png"),
  caption: [Subproceso de Gestión Operativa de Planes de AEP. Nota. Elaboración propia.]
)

Tras el encapsulamiento de la visión pedagógica y estructural de la oferta académica, se hace una revisión a través de un análisis profundo para definir correctamente todos los requerimientos operativos que los modelos demandarán. Esto incluye la identificación de necesidades de personal, infraestructura específica y recursos tecnológicos, transformando la visión estratégica en un conjunto de requerimientos operativos que serán la base para las fases subsiguientes. Si existiera alguna ambigüedad o error, este en consecuencia se propagará y causaría un aumento drástico en la inversión inicial propuesta, ya que provocará ineficiencias en etapas que se centrarán en brindar efectividad a la cadena de valor educativa.

Si bien, en continuación podemos mencionar que, tras el paso de esta tarea, se continúa con la siguiente etapa, la cual resulta en una cadena de tareas y subprocesos, en el cual se deben evaluar las franjas horarias y espacios físicos/virtuales a cada componente del plan educativo (Ver Figura 7).

#figure(
  image("../../src/images/Estructuracion-Gestion-Horarios.png"),
  caption: [Estructuración y Gestión de Horarios. Nota. Elaboración propia.]
)

El proceso de definición resulta muy complejo, de forma que si se tienen muchas facultades, carreras y cada una de estas modifican su modelo educativo central, y agregando que se tiene que manejar en un nivel inter-departamental y regional en cada sede. Resulta en un proceso lento y tardado que conllevaría muchos cuellos de botella y, debido a una mala comunicación, ocasionaría problemas de transición en etapas posteriores. Es de esta manera en que la mayoría de instituciones educativas lidian con esta problemática de optimización, a través del equilibrio centralizado de sede principal, en el que una sede establecida donde se estableció la dirección general, será la que brinde las reglas de negocio y educativas de junta. A pesar de que pueda resultar una solución muy acertada, muchas veces el equilibrar la disponibilidad de recursos (aulas, laboratorios, plataformas virtuales) sigue siendo un problema por el cual se debe optimizar, la cual, como se mencionó antes, sobre la adaptación de currículas, conllevaría en la definición de cargas docentes y las preferencias estudiantiles se convierta en un caos si no se tuvieran en contraparte subdirectores de sede.

Pero a pesar de esto, según reportes realizados por el especialista en gestión educativa García-Peñalvo (2020), la gestión de horarios es inherentemente un problema de asignación de recursos limitados, donde la inteligencia de negocio y, en ocasiones, algoritmos de optimización son esenciales para maximizar la eficiencia y minimizar conflictos. El cual, seguramente muchas instituciones aplican, pero en su mayoría lo hacen utilizando metodologías antiguas de AEP, lo que genera conflicto al momento de querer dinamizar usando recursos antiguos y permisivos que busquen el marco temporal para la operación.

Paralelamente, la identificación y operación de modelos se encarga de traducir los modelos educativos diseñados en estructuras operativas concretas dentro de los sistemas de gestión académica. Esto implica la asignación de códigos, la configuración de parámetros curriculares y la preparación de las colecciones de cursos para su futura implementación. Es una fase de alta dependencia tecnológica, donde la integridad de los datos y la correcta parametrización definen el tener o no errores administrativos que impacten la matrícula o la gestión académica diaria. El resultado es la formalización digital de la oferta educativa, la cual, en conjunto con plataformas que brindan la automatización de cursos y elección de horarios, generan un beneficio directo al estudiante, en el dinamismo y el cambio de la forma en que el estudiante se matricula (Ver Figura 8).

#figure(
  image("../../src/images/Identificacion-Operacion-Modelos.png"),
  caption: "Identificación y Operación de Modelos. Nota. Elaboración propia."
)

Una vez que los modelos educativos han sido operacionalizados y registrados en el sistema, y en conjunción con los cronogramas horarios propuestos, el subproceso se dirige hacia un punto de decisión crítico: la "Agrupación de Recursos y Oportunidades" (Ver Figura 9). Este es un subproceso fundamental que representa la confrontación entre la planificación ideal y la realidad de los recursos institucionales. Aquí, la institución evalúa su capacidad operativa real para respaldar la oferta académica definida. No se trata solo de una verificación de disponibilidad, sino de una validación exhaustiva que permite determinar la viabilidad operativa efectiva de cada plan educativo en función de las necesidades estudiantiles proyectadas y los recursos existentes.

#figure(
  image("../../src/images/Agrupacion-Recursos-Oportunidades.png"),
  caption: "Agrupación de Recursos y Oportunidades. Nota. Elaboración propia"
)

La culminación de este análisis se traduce en una decisión binaria sobre la viabilidad. Si la viabilidad resulta afirmativa, el proceso puede avanzar con la certeza de que los recursos necesarios están disponibles o pueden ser asegurados sin disrupciones mayores. Por el contrario, si la viabilidad no resulta viable, la situación desencadena un proceso de resolución de conflictos adicional y de alta complejidad. Este flujo de excepción es vital para la sostenibilidad del proceso, ya que permite abordar las disparidades entre la demanda y la oferta de recursos. 

El primer paso en esta rama de no viabilidad es la identificación de inconsistencias y Restricciones, una tarea que busca diagnosticar las carencias específicas, ya sean aulas insuficientes, falta de equipamiento técnico especializado o déficit de personal docente cualificado. Tras este diagnóstico, se procede al análisis del impacto de estas restricciones en la oferta educativa. Este análisis cuantifica cómo las limitaciones detectadas pueden afectar la calidad del programa, la capacidad de matrícula o incluso la continuidad de ciertos cursos, lo que permite centrar el enfoque en la mitigación de estas problemáticas operativas.

La continuación de este proceso de mitigación puede resultar en la adquisición de recursos adicionales a entes externos. Esta acción se traduce en la negociación de Materiales Técnicos y Recursos (MTR)#footnote[En un contexto institucional, los recursos MTR se refieren a los Materiales (equipos, software, infraestructura), el Tiempo (plazos, disponibilidad) y los Recursos Humanos (personal técnico, especialistas) necesarios para la operación y el cumplimiento de objetivos establecidos en el plan curricular.]. La importancia de esta negociación radica en que, si los recursos solicitados son aprobados, el proceso retrocede para reevaluar la disponibilidad, asegurando que la nueva dotación se integre y el sistema de planificación se actualice. Sin embargo, si los recursos son negados, se alcanza un punto crítico que exige una propuesta de reajustes mayores al modelo o al horario; lo que implicaría un retorno a fases de diseño de mayor nivel, configurando un flujo de excepción que impacta la planificación inicial y requiere una revisión de junta.

Una vez que la viabilidad operativa ha sido confirmada —ya sea por disponibilidad inicial o mediante una exitosa gestión y adquisición de recursos— y las interacciones inter-departamentales han consolidado las demandas, se procede a las asignaciones finales de estudiantes a módulos y docentes a cursos dentro de cada unidad académica. Esta fase, se caracteriza por la gestión de conflictos a un nivel más granular. A pesar de los esfuerzos de planificación previos, es común que surjan incompatibilidades o solapamientos en las asignaciones detalladas. Por ello, es imperativo que, si se identifican conflictos, todas las incompatibilidades sean resueltas antes de que la AEP por facultad sea confirmada. Una gestión deficiente de estos conflictos a nivel micro no solo derivará en una mala experiencia para el estudiante, afectando su trayectoria académica y satisfacción, sino que también generará problemas sustanciales en la carga de trabajo docente y, en última instancia, comprometerá la continuidad y coherencia académica.

Tras obtener una viabilidad operativa confirmada y la AEP Coherente a Nivel de Facultad, se procede a la fase de formalización y coordinación de los encuentros educativos a un nivel de estabilidad continua. Este paso implica la alineación entre diferentes facultades y la gestión de recursos compartidos a nivel institucional, asegurando que la oferta educativa global sea coherente y coordinada en su conjunto. Este proceso conduce al "Diseño de Órdenes Educativas" (Ver Figura 10), un subproceso donde se formalizan las asignaciones y los cronogramas definitivos para todos los encuentros educativos de la institución.

#figure(
  image("../../src/images/Diseño-Ordenes-Educativas.png"),
  caption: "Diseño de Órdenes Educativas. Nota. Elaboración propia."
)

Una vez que las Órdenes Generales de Encuentros Educativos (OGEE) han sido diseñadas y validadas, el resultado de estos procesos directos y meticulosos se encamina hacia la validación final del plan de estudios. Este hito se materializa a través de la confirmación del esquema y del plan operativo AEP. Esta confirmación representa el sello de aprobación definitivo, que certifica el correcto desarrollo y la preparación integral del sistema para brindar la continuidad educativa establecida como Nivel de Acuerdo de Servicio (SLA) por parte de la institución.

En el contexto actual de la educación, y considerando la complejidad inherente a la ejecución de órdenes educativas derivadas tanto de altas directivas de junta como de la supervisión nacional, la automatización en este punto final adquiere una relevancia crítica. Aunque la confirmación del esquema no siempre es un proceso estandarizado de forma rígida en todas las instituciones, su modernización y planteamiento para la ejecución de la oferta académica demandan la integración de herramientas que minimicen el error humano y eviten los cuellos de botella que surgirían en un manejo manual de volúmenes significativos de datos y decisiones. La capacidad de consolidar y validar automáticamente el plan operativo final brinda confiabilidad y predictibilidad del proceso educativo, lo cual es fundamental para la transición fluida hacia la ejecución real del proceso educativo, asegurando que los estudiantes reciban la oferta académica prometida bajo las mejores condiciones posibles.

=== Análisis del Subproceso de Ejecución del Proceso Educativo
En esta última parte cumbre de desarrollo, la ejecución se basa principalmente en el desarrollo de todos los esfuerzos de diseño, planificación y gestión de recursos; los cuales convergen para poder materializar la experiencia de aprendizaje. Concurrentemente es, en este punto, en el cual representa el punto de contacto directo entre la institución y sus actores principales: los estudiantes y la plana docente. Lo cual, si no se gestiona adecuadamente, podría generar un impacto inmediato en la satisfacción del estudiante, la calidad de la enseñanza y la reputación institucional.

Cabe resaltar que, en etapas previas del proceso, se pretendía poder encapsular la oferta académica a través del establecimiento de cronogramas definidos y asignación de recursos que parte de la oferta académica y la malla curricular, integrándose junto con el modelo educativo por carrera y currícula. En consecuencia, la definición de estos principios operacionales conlleva la habilitación de interacción del estudiante con la oferta; teniendo que cargar de forma muy meticulosa la totalidad de cursos, módulos y programas según el plan operacional establecido. Además, de forma protocolar, se definen fechas límite, se programan las reglas de prerrequisitos y se configuran las aulas virtuales o entornos de aprendizaje dentro de la plataforma de gestión académica, instructiva y operacional. Estos tres subsistemas englobantes en uno mayor de gestión general, permite que tanto los usuarios finales como administrativos no tengan problemas tanto en la comunicación fluida bidireccional que debe existir entre las dos entidades, en caso contrario, se puede asegurar que la falta de disponibilidad ocasionaría la frustración estudiantil y complicación directa en el proceso de inscripción.

Seguidamente, la tarea previa, recae en la adquisición de la oficina de matrículas y admisiones (Subdivisión de SAE#footnote[El Servicio de Apoyo Educativo (SAE) se refiere a los programas y recursos que las instituciones académicas ofrecen para acompañar y asistir a estudiantes con dificultades de aprendizaje o necesidades educativas especiales.]). De forma automática, los registros realizados por los estudiantes son confirmados por el sistema LMS a través del envío de notificaciones de matrícula, en el cual generalmente se detallan las instrucciones, fechas clave y acceso al sistema, el cual debido al tipo de carrera, facultad, promedio ponderado, entre otros filtros definidos como regla de negocio por parte de junta. Si bien, la claridad y anticipación son un factor clave para poder evitar confrontaciones, se debe resaltar mucho más la comunicación tanto implícita como explícita que se tiene. De esta manera, se asegura una inscripción ordenada y se evita la sobrecarga/aglomeraciones o dudas innecesarias, brindando la experiencia directa del estudiante de poder seleccionar sus cursos, validando la trazabilidad generada (generando de esta manera conformidad con prerrequisitos) y la disponibilidad de cupos a cursos con currículas apretadas o gran cantidad de masa estudiantil.

Con la matrícula en curso, de forma organizada y direccionada por la Oficina de Tecnología Educativa / Soporte TI, se asignan los recursos, materiales didácticos, tecnológicos, etc., tanto a docentes como a la plataforma a utilizar para la interacción del servicio educativo. Si bien debido a la manualidad de este proceso, llevado a cabo en su mayoría por el factor administrativo humano, puede no asegurar que el docente pueda disponer de todos los recursos académicos adquiridos, configuración del aula virtual, materiales de explicación, licencias de software necesarias y cualquier otro recurso tecnológico pertinente para la impartición de sus clases; lo cual, no permite que se genere una transición fluida hacia el entorno de aprendizaje y la optimización de las herramientas pedagógicas. Por otro lado, la Oficina de Admisiones y Matrícula se responsabiliza de poder proveer la información de estudiantes y clases de docentes, lo que permite conocer a grupos de trabajo y prepararse para las dinámicas de clase.

El factor central está en la forma de impartición de clases y facilitación de la experiencia de aprendizaje (Ver Figura 11), en este punto la pedagogía persiste de forma continua, a través de la entrega de contenido, la moderación de espacios de debate (foros), la aclaración de dudas y la guía en el proceso de aprendizaje, siendo que estas actividades no solo permitirán medir el progreso del estudiante, sino que también generan datos para la evaluación de la efectividad del proceso educativo. De esta manera, la orquestación de contenidos futuros se derivará de las mejoras operacionales que se le puedan agregar al sistema en favor de la percepción del estudiante en el uso continuo de la plataforma; asegurando que el obstáculo tanto técnico como académico sea atendido oportunamente. Por lo que, en perspectiva la disponibilidad de un sistema, además de su tolerancia a fallos, permiten la retención de la masa estudiantil y la satisfacción general, lo que en definitiva, representa un ciclo continuo de enseñanza-aprendizaje y soporte durante todo el periodo. No menor, las auditorías futuras realizadas aseguran el registro de las calificaciones de los estudiantes, la asistencia completa y la finalización satisfactoria de cursos conforme a la planificación original planteada en la currícula y la propuesta de modelo educativo AEP.

#figure(
  image("../../src/images/Subproceso-Ejecución del Proceso Educativo.png"),
  caption: "Subproceso de Ejecución del Proceso Educativo. Nota. Elaboración propia."
)

== Planificación de Alto Nivel
La transición desde el modelado de procesos de negocio (BPMN) hacia la especificación de requerimientos del sistema es una etapa que traduce las operaciones "cómo se hacen" en las funcionalidades "qué debe hacer" el software.

=== Implementación de Capacidad de Negocio
#figure(
  image("../../src/images/Modelo de Capacidades Skilling.png")
)

=== Levantamiento de Requerimientos


#pagebreak()