server:
  port: 8088

spring:
  application:
    name: reporting-service
  r2dbc:
    url: r2dbc:postgresql://<project-ref>.supabase.co:5432/<db-name> 
    username: postgres
    password: <YOUR_SUPABASE_DB_PASSWORD>
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka # Apunta a tu Eureka Server
    instance:
      hostname: localhost

resilience4j:
  circuitbreaker:
    instances:
      usersService: # Para llamadas a users-service
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
      curriculumService: # Para llamadas a curriculum-service
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
      resourcePlanningService: # Para llamadas a resource-planning-service
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
      enrollmentService: # Para llamadas a enrollment-service
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
      contentService: # Para llamadas a content-service
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
      assessmentsService: # Para llamadas a assessments-service
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10