server:
  port: 8087

spring:
  application:
    name: notifications-service
  r2dbc:
    url: r2dbc:postgresql://<project-ref>.supabase.co:5432/<db-name> 
    username: postgres
    password: <YOUR_SUPABASE_DB_PASSWORD>
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group 
      auto-offset-reset: earliest # O 'latest'
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer # Para recibir JSON
      properties:
        spring.json.trusted.packages: "com.lms.shared.models.*, com.lms.enrollment.event.*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost