server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            enabled: true
            locator:
              enabled: true 
              lower-case-service-id: true 

          routes:
            - id: USERS-SERVICE
              uri: lb://users-service
              predicates:
                - Path=/api/users/**
              filters:
                - RewritePath=/api/users(?<remaining>.*), /api${remaining}
                - name: CircuitBreaker
                  args:
                    name: usersService
                    fallbackUri: forward:/fallback/users

            - id: CURRICULUM-SERVICE
              uri: lb://curriculum-service
              predicates:
                - Path=/api/curriculum/**
              filters:
                - RewritePath=/api/curriculum/(?<remaining>.*), /${remaining}
                - name: CircuitBreaker
                  args:
                    name: curriculumService
                    fallbackUri: forward:/fallback/curriculum

            - id: RESOURCE-PLANNING-SERVICE
              uri: lb://resource-planning-service
              predicates:
                - Path=/api/resource-planning/**
              filters:
                - RewritePath=/api/resource-planning/(?<remaining>.*), /${remaining}
                - name: CircuitBreaker
                  args:
                    name: resourcePlanningService
                    fallbackUri: forward:/fallback/resource-planning

            - id: ENROLLMENT-SERVICE
              uri: lb://enrollment-service
              predicates:
                - Path=/api/enrollment/**
              filters:
                - RewritePath=/api/enrollment/(?<remaining>.*), /${remaining}
                - name: CircuitBreaker
                  args:
                    name: enrollmentService
                    fallbackUri: forward:/fallback/enrollment

            - id: CONTENT-SERVICE
              uri: lb://content-service
              predicates:
                - Path=/api/content/**
              filters:
                - RewritePath=/api/content/(?<remaining>.*), /${remaining}
                - name: CircuitBreaker
                  args:
                    name: contentService
                    fallbackUri: forward:/fallback/content

            - id: ASSESSMENTS-SERVICE
              uri: lb://assessments-service
              predicates:
                - Path=/api/assessments/**
              filters:
                - RewritePath=/api/assessments/(?<remaining>.*), /${remaining}
                - name: CircuitBreaker
                  args:
                    name: assessmentsService
                    fallbackUri: forward:/fallback/assessments

            - id: NOTIFICATIONS-SERVICE
              uri: lb://notifications-service
              predicates:
                - Path=/api/notifications/**
              filters:
                - RewritePath=/api/notifications/(?<remaining>.*), /${remaining}
                - name: CircuitBreaker
                  args:
                    name: notificationsService
                    fallbackUri: forward:/fallback/notifications

            - id: REPORTING-SERVICE
              uri: lb://reporting-service
              predicates:
                - Path=/api/reporting/**
              filters:
                - RewritePath=/api/reporting/(?<remaining>.*), /${remaining}
                - name: CircuitBreaker
                  args:
                    name: reportingService
                    fallbackUri: forward:/fallback/reporting
            
            - id: FINANCIAL-SERVICE
              uri: lb://financial-service
              predicates:
                - Path=/api/financial/**
              filters:
                - RewritePath=/api/financial/(?<remaining>.*), /${remaining}
                - name: CircuitBreaker
                  args:
                    name: reportingService
                    fallbackUri: forward:/fallback/financial

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost
      prefer-ip-address: true

resilience4j:
  circuitbreaker:
    instances:
      usersService:
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
      curriculumService:
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
      resourcePlanningService:
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
      enrollmentService:
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
      contentService:
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
      assessmentsService:
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
      notificationsService:
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
      reportingService:
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
      financialService:
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10