spring:
  application:
    name: curriculum-service 
  config:
    import: "configserver:http://localhost:8888"

SUPABASE_PROJECT_REF_IMPORTED: jtnsigjcpxhkxhpbotkv
SUPABASE_DB_PASSWORD: alternatica-skilling
